base:
  ACCOUNT: da-cpu
  HPSS_PROJECT: emc-da
  DO_JEDIATMVAR: "YES"
  DO_JEDIATMENS: "NO"
  DO_JEDIOCNVAR: "NO"
  DO_JEDILANDDA: "NO"
  DO_MERGENSST: "NO"

atmanl:
  IO_LAYOUT_X: 1
  IO_LAYOUT_Y: 1
